#!/usr/bin/env bash
#install your load balancer

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5889-webs
    bind *:80
    mode http
    balance roundrobin
    server 5889-web-01 54.91.127.208:80 check
    server 5889-web-02 54.87.90.200:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
